### ISSUE TITLE
why "onclick" can't work 

### ISSUE THREAD

**Issue by 0ui0** [MithrilJS/mithril-node-render#98]
![image](https://user-images.githubusercontent.com/17251475/98247003-072b9780-1fae-11eb-889a-3a1266db14cc.png)
the html will  render become 
`<div><div>here?</div><button>button</button></div>`
it can only render static content?

**Comment by isiahmeadows** [comment]
Please prefer to post self-contained reproductions that can be directly executed or easily copied into a file that itself can be executed. Pictures of code snippets from your editor don't tick either of these boxes.

> it can only render static content?

This is correct and in line with tooling from other libraries like React and Vue. It does *not* try to render function values, as those cannot be represented in the HTML DOM in general, and even if we were to try to make exceptions, one of the risks is errors due to closure variables (including the view's `vnode` parameter - it's very often that you want to do `vnode.attrs` in an event handler) not existing in scope and such.

**Comment by 0ui0** [comment]
Oh, I see
Thanks reply~ (ˊωˋ*)
